# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1192, 50)
        Form.setStyleSheet("QWidget{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.528136, x2:1, y2:0.517, stop:0 rgba(86, 255, 109, 255), stop:1 rgba(158, 221, 185, 255));\n"
"/*background-color: rgb(170, 255, 127);*/\n"
"}\n"
"QLabel,QComboBox,QPushButton{\n"
"    background-color:none;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 12pt \"黑体\";\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(28, 58, 255);\n"
"}")
        self.label_id = QtWidgets.QLabel(Form)
        self.label_id.setGeometry(QtCore.QRect(8, 10, 50, 30))
        self.label_id.setAlignment(QtCore.Qt.AlignCenter)
        self.label_id.setObjectName("label_id")
        self.btn_count = QtWidgets.QPushButton(Form)
        self.btn_count.setGeometry(QtCore.QRect(460, 10, 50, 30))
        self.btn_count.setObjectName("btn_count")
        self.label_number = QtWidgets.QLabel(Form)
        self.label_number.setGeometry(QtCore.QRect(80, 10, 60, 30))
        self.label_number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number.setObjectName("label_number")
        self.label_create_time = QtWidgets.QLabel(Form)
        self.label_create_time.setGeometry(QtCore.QRect(655, 10, 150, 30))
        self.label_create_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_create_time.setObjectName("label_create_time")
        self.label_task = QtWidgets.QLabel(Form)
        self.label_task.setGeometry(QtCore.QRect(150, 10, 200, 31))
        self.label_task.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task.setObjectName("label_task")
        self.btn_view = QtWidgets.QPushButton(Form)
        self.btn_view.setGeometry(QtCore.QRect(350, 10, 70, 30))
        self.btn_view.setObjectName("btn_view")
        self.label_update_time = QtWidgets.QLabel(Form)
        self.label_update_time.setGeometry(QtCore.QRect(810, 10, 150, 30))
        self.label_update_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_update_time.setObjectName("label_update_time")
        self.btn_history = QtWidgets.QPushButton(Form)
        self.btn_history.setGeometry(QtCore.QRect(1090, 10, 50, 30))
        self.btn_history.setObjectName("btn_history")
        self.comboBox_participator = QtWidgets.QComboBox(Form)
        self.comboBox_participator.setGeometry(QtCore.QRect(980, 13, 80, 25))
        self.comboBox_participator.setObjectName("comboBox_participator")
        self.comboBox_participator.addItem("")
        self.comboBox_participator.addItem("")
        self.comboBox_participator.addItem("")
        self.combox_schedule = QtWidgets.QComboBox(Form)
        self.combox_schedule.setGeometry(QtCore.QRect(560, 13, 80, 25))
        self.combox_schedule.setObjectName("combox_schedule")
        self.combox_schedule.addItem("")
        self.combox_schedule.addItem("")
        self.combox_schedule.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_id.setText(_translate("Form", "2"))
        self.btn_count.setText(_translate("Form", "3"))
        self.label_number.setText(_translate("Form", "50049"))
        self.label_create_time.setText(_translate("Form", "2022.1.21 10：30"))
        self.label_task.setText(_translate("Form", "Solar Survey"))
        self.btn_view.setText(_translate("Form", "view"))
        self.label_update_time.setText(_translate("Form", "2022.1.30 9：20"))
        self.btn_history.setText(_translate("Form", "历史"))
        self.comboBox_participator.setItemText(0, _translate("Form", "刘璇"))
        self.comboBox_participator.setItemText(1, _translate("Form", "丁梓靖"))
        self.comboBox_participator.setItemText(2, _translate("Form", "赵银鹏"))
        self.combox_schedule.setItemText(0, _translate("Form", "完成"))
        self.combox_schedule.setItemText(1, _translate("Form", "未完成"))
        self.combox_schedule.setItemText(2, _translate("Form", "详情"))
