# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScriptManagement.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1240, 733)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("QWidget{\n"
"background-color: rgb(204, 204, 204);\n"
"}\n"
"QLabel,QLineEdit{\n"
"    color: rgb(0, 0, 0);\n"
"    font: 12pt \"黑体\";\n"
"}\n"
"QLineEdit{\n"
"    color: rgb(0, 85, 255);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    color: rgb(84, 84, 84);\n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget_5 = QtWidgets.QWidget(self.page)
        self.widget_5.setGeometry(QtCore.QRect(10, 20, 1201, 541))
        self.widget_5.setStyleSheet("background-color: rgb(180, 180, 180);")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_5)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_4.setMaximumSize(QtCore.QSize(1180, 60))
        self.widget_4.setStyleSheet("QWidget{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QLabel{\n"
"    color:rgb(120, 174, 255);\n"
"    \n"
"    font: 12pt \"黑体\";\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.label_16 = QtWidgets.QLabel(self.widget_4)
        self.label_16.setGeometry(QtCore.QRect(70, 16, 91, 31))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget_4)
        self.label_17.setGeometry(QtCore.QRect(450, 16, 81, 31))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.widget_4)
        self.label_18.setGeometry(QtCore.QRect(190, 16, 111, 31))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.widget_4)
        self.label_19.setGeometry(QtCore.QRect(350, 16, 71, 31))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.widget_4)
        self.label_20.setGeometry(QtCore.QRect(8, 16, 51, 31))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_4)
        self.label_21.setGeometry(QtCore.QRect(560, 16, 81, 31))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_4)
        self.label_22.setGeometry(QtCore.QRect(690, 16, 81, 31))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.widget_4)
        self.label_23.setGeometry(QtCore.QRect(840, 16, 81, 31))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.widget_4)
        self.label_24.setGeometry(QtCore.QRect(970, 16, 81, 31))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.widget_4)
        self.label_25.setGeometry(QtCore.QRect(1070, 16, 81, 31))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget_5)
        self.widget_2.setEnabled(True)
        self.widget_2.setMinimumSize(QtCore.QSize(2, 50))
        self.widget_2.setMaximumSize(QtCore.QSize(1180, 50))
        self.widget_2.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.528136, x2:1, y2:0.517, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(187, 187, 187, 255));\n"
"/*background-color: rgb(255, 255, 255);*/\n"
"}\n"
"QLabel,QComboBox,QPushButton{\n"
"background-color:none;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 12pt \"黑体\";\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(28, 58, 255);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_2.setGeometry(QtCore.QRect(560, 13, 80, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(80, 10, 60, 30))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(150, 10, 200, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(8, 10, 50, 30))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(350, 10, 70, 30))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(655, 10, 150, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(460, 10, 50, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(810, 10, 150, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_4.setGeometry(QtCore.QRect(980, 13, 80, 25))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_7.setGeometry(QtCore.QRect(1090, 10, 50, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_5)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(1180, 50))
        self.widget.setStyleSheet("QWidget{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.528136, x2:1, y2:0.517, stop:0 rgba(86, 255, 109, 255), stop:1 rgba(158, 221, 185, 255));\n"
"/*background-color: rgb(170, 255, 127);*/\n"
"}\n"
"QLabel,QComboBox,QPushButton{\n"
"    background-color:none;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 12pt \"黑体\";\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(28, 58, 255);\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(560, 13, 80, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(80, 10, 60, 30))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 200, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setGeometry(QtCore.QRect(8, 10, 50, 30))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 10, 70, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(655, 10, 150, 30))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(460, 10, 50, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(810, 10, 150, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.comboBox_5 = QtWidgets.QComboBox(self.widget)
        self.comboBox_5.setGeometry(QtCore.QRect(980, 13, 80, 25))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setGeometry(QtCore.QRect(1090, 10, 50, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.widget, 2, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget_5)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_3.setMaximumSize(QtCore.QSize(1180, 50))
        self.widget_3.setStyleSheet("QWidget{\n"
"    background-color: qlineargradient(spread:reflect, x1:1, y1:0.528, x2:0.057, y2:0.54, stop:0 rgba(215, 226, 185, 255), stop:1 rgba(216, 235, 13, 255));\n"
"/*background-color: rgb(255, 255, 127);*/\n"
"}\n"
"QLabel,QComboBox,QPushButton{\n"
"    background-color:none;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 12pt \"黑体\";\n"
"}\n"
"QPushButton{\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(28, 58, 255);\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_3.setGeometry(QtCore.QRect(560, 13, 80, 25))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(80, 10, 60, 30))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setGeometry(QtCore.QRect(150, 10, 200, 31))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_15 = QtWidgets.QLabel(self.widget_3)
        self.label_15.setGeometry(QtCore.QRect(8, 10, 50, 30))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_3.setGeometry(QtCore.QRect(350, 10, 70, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setGeometry(QtCore.QRect(655, 10, 150, 30))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_6.setGeometry(QtCore.QRect(460, 10, 50, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(810, 10, 150, 30))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.comboBox_6 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_6.setGeometry(QtCore.QRect(980, 13, 80, 25))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_9.setGeometry(QtCore.QRect(1090, 10, 50, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.widget_3, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.page)
        self.widget_6.setGeometry(QtCore.QRect(10, 590, 321, 80))
        self.widget_6.setStyleSheet("background-color: rgb(154, 154, 154);")
        self.widget_6.setObjectName("widget_6")
        self.checkBox = QtWidgets.QCheckBox(self.widget_6)
        self.checkBox.setGeometry(QtCore.QRect(10, 7, 121, 16))
        self.checkBox.setMinimumSize(QtCore.QSize(121, 16))
        self.checkBox.setMaximumSize(QtCore.QSize(121, 16))
        self.checkBox.setStyleSheet("QCheckBox{\n"
"    color: rgb(0, 0, 0);\n"
"    font: 10pt \"黑体\";\n"
"}")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.label_28 = QtWidgets.QLabel(self.widget_6)
        self.label_28.setGeometry(QtCore.QRect(10, 34, 54, 31))
        self.label_28.setObjectName("label_28")
        self.widget1 = QtWidgets.QWidget(self.widget_6)
        self.widget1.setGeometry(QtCore.QRect(53, 37, 179, 33))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(118, 31))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(118, 31))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"color: rgb(252, 252, 252);\n"
"font-size:13pt;\n"
"background-color: rgb(80, 76, 70);\n"
"border:1px solid rgb(238, 238, 238);\n"
"border-right:none;\n"
"border-top-left-radius:5px;\n"
"border-bottom-left-radius:5px;\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_11.setMinimumSize(QtCore.QSize(51, 31))
        self.pushButton_11.setMaximumSize(QtCore.QSize(51, 31))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"border:1px solid rgb(255, 255, 255);\n"
"border-left:none;\n"
"border-top-right-radius:5px;\n"
"border-bottom-right-radius:5px;\n"
"color: rgb(255, 255, 255);\n"
"background-color:rgb(170, 85, 0);\n"
"font: 13pt \"华文琥珀\";\n"
"}\n"
"QPushButton:pressed{\n"
"font-size:10px;\n"
"background-color:rgb(95, 48, 0);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_26 = QtWidgets.QLabel(self.page_2)
        self.label_26.setGeometry(QtCore.QRect(500, 410, 51, 51))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(570, 410, 200, 40))
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_27 = QtWidgets.QLabel(self.page_2)
        self.label_27.setGeometry(QtCore.QRect(500, 480, 51, 51))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(570, 480, 200, 40))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_10.setGeometry(QtCore.QRect(540, 560, 111, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_12.setGeometry(QtCore.QRect(710, 560, 111, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1240, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_16.setText(_translate("MainWindow", "脚本编号"))
        self.label_17.setText(_translate("MainWindow", "被使用次数"))
        self.label_18.setText(_translate("MainWindow", "任务名称"))
        self.label_19.setText(_translate("MainWindow", "阅览脚本"))
        self.label_20.setText(_translate("MainWindow", "ID"))
        self.label_21.setText(_translate("MainWindow", "完成情况"))
        self.label_22.setText(_translate("MainWindow", "创建时间"))
        self.label_23.setText(_translate("MainWindow", "修改时间"))
        self.label_24.setText(_translate("MainWindow", "参与者"))
        self.label_25.setText(_translate("MainWindow", "操作记录"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "未完成"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "完成"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "详情"))
        self.label_5.setText(_translate("MainWindow", "50049"))
        self.label_7.setText(_translate("MainWindow", "Solar Survey"))
        self.label_13.setText(_translate("MainWindow", "1"))
        self.pushButton.setText(_translate("MainWindow", "None"))
        self.label_3.setText(_translate("MainWindow", "2022.1.21 10：30"))
        self.pushButton_4.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "2022.1.30 9：20"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "刘璇"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "丁梓靖"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "赵银鹏"))
        self.pushButton_7.setText(_translate("MainWindow", "历史"))
        self.comboBox.setItemText(0, _translate("MainWindow", "完成"))
        self.comboBox.setItemText(1, _translate("MainWindow", "未完成"))
        self.comboBox.setItemText(2, _translate("MainWindow", "详情"))
        self.label.setText(_translate("MainWindow", "50049"))
        self.label_2.setText(_translate("MainWindow", "Solar Survey"))
        self.label_14.setText(_translate("MainWindow", "2"))
        self.pushButton_2.setText(_translate("MainWindow", "view"))
        self.label_8.setText(_translate("MainWindow", "2022.1.1 11：20"))
        self.pushButton_5.setText(_translate("MainWindow", "3"))
        self.label_6.setText(_translate("MainWindow", "2022.12.30 6：03"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "刘璇"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "丁梓靖"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "赵银鹏"))
        self.pushButton_8.setText(_translate("MainWindow", "历史"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "详情"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "完成"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "未完成"))
        self.label_9.setText(_translate("MainWindow", "50049"))
        self.label_11.setText(_translate("MainWindow", "Solar Survey"))
        self.label_15.setText(_translate("MainWindow", "3"))
        self.pushButton_3.setText(_translate("MainWindow", "view"))
        self.label_12.setText(_translate("MainWindow", "2022.1.10 1:11"))
        self.pushButton_6.setText(_translate("MainWindow", "1"))
        self.label_10.setText(_translate("MainWindow", "2022.1.30 9：34"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "刘璇"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "丁梓靖"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "赵银鹏"))
        self.pushButton_9.setText(_translate("MainWindow", "历史"))
        self.checkBox.setText(_translate("MainWindow", "只显示个人脚本"))
        self.label_28.setText(_translate("MainWindow", "编号"))
        self.pushButton_11.setText(_translate("MainWindow", "OK"))
        self.label_26.setText(_translate("MainWindow", "姓名"))
        self.label_27.setText(_translate("MainWindow", "密码"))
        self.pushButton_10.setText(_translate("MainWindow", "登录"))
        self.pushButton_12.setText(_translate("MainWindow", "注册"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.action.setText(_translate("MainWindow", "新建脚本"))
        self.action_2.setText(_translate("MainWindow", "修改脚本"))
