# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JSM_BackgroundSystem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QTreeWidgetItem
from PyQt5 import QtCore, QtGui, QtWidgets
from core.utility import (
    QApplication,
    QMainWindow,
    QtCore,
    QWidget,
    QGridLayout
)
from GuiLib import Tree

from core.JSM_b_system.Js_exploitation_UI import JSExploitation
from core.JSM_b_system.js_ranking_UI import JSRanking
from core.JSM_b_system.personage_js_UI import PersonageJS

class JSMBSystemp(QMainWindow):
    def __init__(self, *args,**kwargs) -> None:
        super().__init__(*args,**kwargs)

        # 所有界面类名了列表(这里必须是类名,不能是实例名,且要有一定的顺序,需要继承QWidget)
        self.__UI_class_name = [JSExploitation,JSRanking,PersonageJS]
        self.setupUi()
        self.Init()

    def uiClassName(self)->list:
        return self.__UI_class_name

    def Init(self):
        # 创建树
        self.treeWidget.createTree({
            "脚本开发人员":["刘璇","丁梓靖","赵银鹏"],
            "脚本使用次数排名":"",
            "脚本活跃图像":""
        })
        # 创建界面
        for ui in self.uiClassName():
            self.addUI(ui())

        # 方法测试,展示新增页面
        self.stackedWidget.setCurrentIndex(self.stackedWidget.count()-1)

    def addTree(self):
        pass

    def setupUi(self):
        self.setObjectName("self")
        self.resize(1211, 718)
        self.setStyleSheet("QWidget{\n"
"    font: 11pt \"黑体\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget = Tree(self.centralwidget)
        self.treeWidget.setMinimumSize(QtCore.QSize(251, 0))
        self.treeWidget.setMaximumSize(QtCore.QSize(251, 16777215))
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        # self.stackedWidget.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.setCentralWidget(self.centralwidget)
        #
        # self.menubar = QtWidgets.QMenuBar(self)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1211, 21))
        # self.menubar.setObjectName("menubar")
        # self.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(self)
        # self.statusbar.setObjectName("statusbar")
        # self.setStatusBar(self.statusbar)

        self.retranslateUi()
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def addUI(self,widget:QWidget):
        baseUI = QWidget()
        # 创建网格布局
        gbox = QGridLayout()
        gbox.setContentsMargins(1,0,0,0)
        baseUI.setLayout(gbox)
        # 将界面添加到网格布局中
        gbox.addWidget(widget,0,0)

        self.stackedWidget.addWidget(baseUI)

    
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "JSM后台"))


if __name__ == '__main__':
    app = QApplication(sys.argv)

    win = JSMBSystemp()
    win.show()

    sys.exit(app.exec_())
    