# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from core.utility import sys,typing

from core.utility import (
    QApplication,
    QWidget,
    QVBoxLayout
)

from core.card import TitleCard,Card
from core.cardframe.cardframeBody import CardFrameBody

# 设置
class CardFrame(QWidget):
    def __init__(self, *args,**kwargs) -> None:
        super().__init__(*args,**kwargs)

        self.setupUi()
        self.defaultStyleSheet()

    
    def setupUi(self):
        self.resize(1240, 700)
        # 创建布局
        self.var_body = QVBoxLayout(self)
        self.var_body.setContentsMargins(0, 0, 0, 0)
        self.var_body.setSpacing(0)

        # 添加表头
        self.var_body.addWidget(TitleCard())

        # 卡片
        self.card_body = CardFrameBody(self)
        self.var_body.addWidget(self.card_body)

    # 给外部卡片对象
    def external_cardBodyObj(self)->CardFrameBody:
        return self.card_body

    def defaultStyleSheet(self):
        self.setStyleSheet('''
        border:none;
        ''')

    # 在底部添加窗口
    def endWidget(self,widget:QWidget):
        self.var_body.addWidget(widget)

    def cardInfoAll(self)->typing.List[Card]:
        temp =[obj for obj in self.card_body.card()]
        return temp

    # 根据索引获取卡片信息
    def getCardInfo(self,id:int)->Card:
        # 二分查找
        left = 0
        right = len(self.cardInfoAll()) - 1
        while left <= right:
            mid = (left + right) // 2
            if int(self.cardInfoAll()[mid].id_()) == id:
                return self.cardInfoAll()[mid]
            elif int(self.cardInfoAll()[mid].id_()) > id:
                right = mid - 1
            else:
                left = mid + 1
        return None

if __name__ == '__main__':
    app = QApplication(sys.argv)

    win = CardFrame()
    win.show()
    print(win.getCardInfo(2))

    sys.exit(app.exec_())

