# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.QtWidgets import QApplication, QWidget,QVBoxLayout
from PyQt5 import QtCore, QtGui, QtWidgets


from core.card import TitleCard
from core.cardframe.cardframeBody import CardFrameBody

# 设置
class CardFrame(QWidget):
    def __init__(self, *args,**kwargs) -> None:
        super().__init__(*args,**kwargs)

        self.setupUi()
        self.defaultStyleSheet()

    
    def setupUi(self):
        self.resize(1240, 700)
        # 创建布局
        self.var_body = QVBoxLayout(self)
        self.var_body.setContentsMargins(0, 0, 0, 0)
        self.var_body.setSpacing(0)

        # 添加表头
        self.var_body.addWidget(TitleCard())

        # 卡片
        self.card_body = CardFrameBody(self)
        self.var_body.addWidget(self.card_body)

    # 给外部卡片对象
    def external_cardBodyObj(self)->CardFrameBody:
        return self.card_body

    def defaultStyleSheet(self):
        self.setStyleSheet('''
        border:none;
        ''')

    # 在底部添加窗口
    def endWidget(self,widget:QWidget):
        self.var_body.addWidget(widget)



if __name__ == '__main__':
    app = QApplication(sys.argv)

    win = CardFrame()
    win.show()

    sys.exit(app.exec_())

