# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'countView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5 import QtCore, QtGui, QtWidgets

from GuiLib import ListWidget
from GuiLib import Table

class CountView(QWidget):
    def __init__(self, *args,**kwargs) -> None:
        super().__init__(*args,**kwargs)
        self.setupUi()
    
    def setupUi(self):
        self.setObjectName("self")
        self.resize(906, 492)
        self.setStyleSheet("WQidegt{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setContentsMargins(3, 3, 0, 3)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = ListWidget(self)
        self.listWidget.setMinimumSize(QtCore.QSize(231, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(231, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setStyleSheet('''
QWidget#listWidget{
font: 12pt "黑体";
border:none;
border-right:1px solid gray;
background-color:rgb(157, 157, 157); 
color:rgb(255, 255, 255);
}''')
        self.gridLayout.addWidget(self.listWidget, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.widget.setObjectName("widget")
        self.tableWidget = Table(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 30, 551, 371))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    # 创建信息
    def createList(self,number_list:list):
        self.clearList()
        for text in number_list:
            self.listWidget.addList(text)

    # 设置标题
    def setTitle(self,text:str):
        self.setWindowTitle(text)

    def clearList(self):
        self.listWidget.clearList()


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)

if __name__ == '__main__':
    app = QApplication(sys.argv)

    win = CountView()
    win.show()

    sys.exit(app.exec_())
    