# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'deleteJS.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5 import QtCore, QtGui, QtWidgets



class DeleteJS(QWidget):
    def __init__(self, *args,**kwargs) -> None:
        super().__init__(*args,**kwargs)
        self.setupUi()
    
    def setupUi(self):
        self.setObjectName("self")
        self.resize(771, 421)
        self.setMinimumSize(QtCore.QSize(771, 421))
        self.setMaximumSize(QtCore.QSize(771, 421))
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self)
        self.widget.setMinimumSize(QtCore.QSize(291, 421))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 421))
        self.widget.setStyleSheet("background-color: rgb(173, 178, 255);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(140, 30, 131, 51))
        self.label.setStyleSheet("QLabel{\n"
"    font: 40pt \"Heiti SC\";\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 100, 201, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.btn_find = QtWidgets.QPushButton(self.widget)
        self.btn_find.setGeometry(QtCore.QRect(150, 180, 113, 32))
        self.btn_find.setObjectName("btn_find")
        self.btn_del = QtWidgets.QPushButton(self.widget)
        self.btn_del.setGeometry(QtCore.QRect(90, 350, 231, 61))
        self.btn_del.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"    border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 24pt \"Baoli SC\";\n"
"}")
        self.btn_del.setObjectName("btn_del")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self)
        self.widget_2.setMinimumSize(QtCore.QSize(371, 421))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 421))
        self.widget_2.setStyleSheet("background-color: rgb(113, 247, 255);")
        self.widget_2.setObjectName("widget_2")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 361, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.label.setText(_translate("self", "脚本"))
        self.btn_find.setText(_translate("self", "查询"))
        self.btn_del.setText(_translate("self", "删除"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("self", "新建行"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("self", "新建行"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("self", "新建行"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("self", "新建行"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("self", "新建行"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("self", "标签"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("self", "内容"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("self", "ID"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("self", "1"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("self", "编号"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("self", "9001"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("self", "标题"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("self", "hello world"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("self", "创建者"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("self", "LX"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("self", "删除权限"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("self", "可删除|禁止删除|密码删除"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

if __name__ == '__main__':
    app = QApplication(sys.argv)

    win = DeleteJS()
    win.show()

    sys.exit(app.exec_())
    