# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'open_load.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import typing

from PyQt5.QtCore import QPoint, QThread, QObject
from PyQt5.QtGui import QMouseEvent
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget, QProgressBar
from PyQt5 import QtCore, QtGui, QtWidgets


class ProgressBarThread(QProgressBar,QThread):

    def __init__(self, *args,**kwargs) -> None:
        super().__init__(*args,**kwargs)


class OpenLoad(QWidget):
    def __init__(self, *args,**kwargs) -> None:
        super().__init__(*args,**kwargs)
        self.setupUi()

        # 设置窗体无边框
        self.setWindowFlags(Qt.FramelessWindowHint)
        # 设置背景透明
        # self.setAttribute(Qt.WA_TranslucentBackground)
    
    def setupUi(self):
        self.setObjectName("self")
        self.resize(464, 429)
        self.setMinimumSize(QtCore.QSize(464, 429))
        self.setMaximumSize(QtCore.QSize(464, 429))
        self.setStyleSheet('''
QWidget{
	background-color: qlineargradient(spread:pad, x1:0.023, y1:0.023, x2:1, y2:1, stop:0 rgba(130, 247, 255, 255), stop:1 rgba(190, 191, 221, 255));
}
        ''')
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(250, 90, 161, 281))
        self.label_2.setStyleSheet("QLabel{\n"
"font:200pt \"黑体\";\n"
"background-color: none;\n"
"/*color: rgb(170, 255, 255);*/\n"
"    color:qlineargradient(spread:pad, x1:0.295955, y1:0.471, x2:0.54, y2:0.619273, stop:0.488636 rgba(34, 178, 221, 216));\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(100, 0, 161, 281))
        self.label.setStyleSheet("QLabel{\n"
"font:200pt \"黑体\";\n"
"background-color: none;\n"
"color:qlineargradient(spread:pad, x1:0.295955, y1:0.471, x2:0.54, y2:0.619273, stop:0.488636 rgba(125, 60, 221, 77))\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 111, 21))
        self.label_3.setStyleSheet("QWidget{\n"
"    background-color:none;\n"
"color:gray;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(self)
        self.progressBar.setGeometry(QtCore.QRect(0, 423, 464, 5))
        self.progressBar.setStyleSheet("QWidget{\n"
"    color:rgb(68, 68, 68);\n"
"    background-color: rgb(76, 76, 76);\n"
"}\n"
"QProgressBar::chunk{\n"
"    background-color: rgb(170, 255, 127);\n"
"}")
        self.progressBar.setProperty("value", 80)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.textEdit = QtWidgets.QTextEdit(self)
        self.textEdit.setGeometry(QtCore.QRect(10, 260, 221, 121))
        self.textEdit.setStyleSheet("QTextEdit{\n"
"color:gray;\n"
"border:none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.295955, y1:0.471, x2:0.705, y2:0.778, stop:0.488636 rgba(34, 178, 221, 5));\n"
"}")
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def mousePressEvent(self, e: QMouseEvent) -> None:
        if e.button() == Qt.LeftButton:
            self._isTracking = True
            self._startPos = QPoint(e.x(), e.y())

    def mouseMoveEvent(self, e:QMouseEvent) -> None:
        try:
            self._endPos = e.pos() - self._startPos
            self.move(self.pos() + self._endPos)
        except Exception as e:
            pass

    def mouseReleaseEvent(self, e: QMouseEvent):
        if e.button() == Qt.LeftButton:
            self._isTracking = False


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.label_2.setText(_translate("self", "S"))
        self.label.setText(_translate("self", "J"))
        self.label_3.setText(_translate("self", "@ LX"))
        self.textEdit.setHtml(_translate("self", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dsadsa..................加载中</p></body></html>"))

if __name__ == '__main__':
    app = QApplication(sys.argv)

    win = OpenLoad()
    win.show()

    sys.exit(app.exec_())
    