# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5 import QtCore, QtGui, QtWidgets


from core.utility import Mysql_PersonalInfo


# 注册
class Register(QWidget):
    def __init__(self, *args,**kwargs) -> None:
        super().__init__(*args,**kwargs)
        self.setupUi()
        # 信息
        self.__info = None
        self.myEvent()
        self.Init()
    
    def setupUi(self):
        self.setObjectName("self")
        self.resize(685, 518)
        # 固定窗口大小
        self.setFixedSize(self.width(), self.height())

        self.setStyleSheet("QWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(140, 90, 371, 301))
        self.widget.setStyleSheet("QWidget{\n"
"    background-color:none;\n"
"font: 12pt \"黑体\";\n"
"    border:none;\n"
"}\n"
"QLabel,QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    font: 12pt \"黑体\";\n"
"}")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(140, 240, 101, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: rgb(59, 59, 59);\n"
"background-color: rgb(85, 255, 127);\n"
"border-radius:5px;\n"
"border:1px solid rgb(165, 165, 165);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(0, 255, 0);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 110, 211, 40))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border:1px solid rgb(65, 65, 65);\n"
"border-radius:5px;\n"
"font: 75 10pt \"微软雅黑\";\n"
"}\n"
"QLineEdit:focus{\n"
"border:1px solid rgb(0, 170, 255);\n"
"}")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 50, 211, 40))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border:1px solid rgb(65, 65, 65);\n"
"border-radius:5px;\n"
"font: 75 10pt \"微软雅黑\";\n"
"}\n"
"QLineEdit:focus{\n"
"border:1px solid rgb(0, 170, 255);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 170, 211, 40))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"border:1px solid rgb(65, 65, 65);\n"
"border-radius:5px;\n"
"font: 75 10pt \"微软雅黑\";\n"
"}\n"
"QLineEdit:focus{\n"
"border:1px solid rgb(0, 170, 255);\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 175, 81, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 55, 81, 41))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(35, 120, 61, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def Init(self):

        self.smj_personal_info = Mysql_PersonalInfo()
        self.lineEdit.setText("")
        self.lineEdit_2.setText("")
        self.lineEdit_3.setText("")

    def registerEvent(self):
        name = self.lineEdit.text()
        password = self.lineEdit_2.text()
        password2 = self.lineEdit_3.text()

        if name == "" or password == "" or password2 == "":
            QtWidgets.QMessageBox.warning(self, "警告", "请填写完整信息")
            return
        if password != password2:
            QtWidgets.QMessageBox.warning(self, "警告", "两次密码不一致")
            return
        if len(password) < 6:
            QtWidgets.QMessageBox.warning(self, "警告", "密码长度不能小于6位")
            return
        if not self.smj_personal_info.is_exist(name):
            QtWidgets.QMessageBox.information(self, "提示", "注册成功")
            self.smj_personal_info.insert(name, password)
            self.close()
        else:
            QtWidgets.QMessageBox.warning(self, "警告", "用户名已存在")
            return
        self.__info = [name, password]

    # 返回个人信息
    def getInfo(self):
        return self.__info

    def myEvent(self):
        self.pushButton.clicked.connect(self.registerEvent)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "jsm注册"))
        self.pushButton.setText(_translate("self", "注册"))
        self.label_3.setText(_translate("self", "确认密码*:"))
        self.label.setText(_translate("self", "姓名*:"))
        self.label_2.setText(_translate("self", "密码*:"))

if __name__ == '__main__':
    app = QApplication(sys.argv)

    win = Register()
    win.show()

    sys.exit(app.exec_())
    