# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from random import randint
from PyQt5.QtWidgets import QApplication, QWidget,QPushButton,QScrollArea
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal


class MyQScrollArea(QScrollArea):
    scrolled = pyqtSignal(bool)

    def __init__(self, *args,**kwargs) -> None:
        super().__init__(*args,**kwargs)


    def wheelEvent(self, e: QtGui.QWheelEvent) -> None:
        self.scrolled.emit(True)

        super(MyQScrollArea, self).wheelEvent(e)

class Test(QWidget):
    def __init__(self, *args,**kwargs) -> None:
        super().__init__(*args,**kwargs)
        self.setupUi()
        self.btn = QPushButton(self)
        self.btn.setText("增加")
        self.btn.clicked.connect(self.add)
        self.btn_list = []
        for i in range(25):
            bt = QPushButton(self.scrollAreaWidgetContents)
            bt.setText(str(randint(1, 1000)))
            self.btn_list.append(bt)

    def add(self):
        if self.btn_list:
            # bt = QPushButton(self.scrollAreaWidgetContents)
            # bt.setText(str(randint(1,1000)))
            self.verticalLayout.addWidget(self.btn_list.pop())
        else:
            print("到底了")


    def setupUi(self):
        self.setObjectName("self")
        self.resize(631, 466)
        self.scrollArea = MyQScrollArea(self)
        self.scrollArea.scrolled.connect(self.add)

        self.scrollArea.setGeometry(QtCore.QRect(110, 60, 401, 311))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setMinimumHeight(900)
        # self.scrollAreaWidgetContents.resize(self.width(),900)
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 399, 800))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.pushButton.setText(_translate("self", "PushButton"))
        self.pushButton_2.setText(_translate("self", "PushButton"))



if __name__ == '__main__':
    app = QApplication(sys.argv)

    win = Test()
    win.show()

    sys.exit(app.exec_())
    